name: poi-api
on:
  push:
    branches:
    - master
env:
  REGION: us-east1-a
  PROJECT_ID: mvillarrealb-demo-platform
  BASE_IMAGE: gcr.io/mvillarrealb-demo-platform/poi-api
  DATABASE_INSTANCE: mvillarrealb-pg-sql
  SERVICE_NAME: poi-api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project
        id: checkout
        uses: actions/checkout@master
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          username: secrets
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          push: true
          tags: $BASE_IMAGE:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          region: $REGION
          service: $SERVICE_NAME
          image: $BASE_IMAGE/${{ github.sha }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }},DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}"
          flags: "--add-cloudsql-instances '$PROJECT_ID:$REGION:$DATABASE_INSTANCE'"
  test:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    steps:
      - name: Run e2e Test
        uses: matt-ball/newman-action@master
        id: test
        with:
          collection: postman_collection.json